apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynameis-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynameis
      env: blue
  template:
    metadata:
      labels:
        app: mynameis
        env: blue
    spec:
      containers:
        - name: mynameis
          image: locbuii/mynameis:latest
          ports:
            - containerPort: 80
