apiVersion: v1
kind: Service
metadata:
  name: mynameis-blue-service
spec:
  selector:
    app: mynameis
    env: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
