apiVersion: v1
kind: Service
metadata:
  name: mynameis-green-service
spec:
  selector:
    app: mynameis
    env: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
