version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.12

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14

      - run:
          name: Install hadolint
          command: sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m) && sudo chmod +x /bin/hadolint

      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile
          
      - run:
          name: Build and Push Docker Image
          command: |
            docker --version
            docker build -t mynameis .
            docker tag mynameis locbuii/mynameis:latest
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push locbuii/mynameis:latest
            
      - run:
          name: Install eksctl
          command: |
            sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | sudo tar xz -C /usr/local/bin

      - run:
          name: Create EKS cluster
          command: eksctl create cluster --name my-cluster --region us-west-2 --node-type t2.micro --nodes-min 1 --nodes-max 3

      - run:
          name: Configure kubectl
          command: eksctl utils write-kubeconfig --name my-cluster --region us-west-2
      
      - run:
          name: Install kubectl
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https
            curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
            sudo apt-get update
            sudo apt-get install -y kubectl
            
      - run:
          name: Verify kubectl installation
          command: kubectl version --client

      - run:
          name: Deploy to Kubernetes Cluster
          command: |
            aws eks update-kubeconfig --name mynameis-cluster --region us-east-1
            kubectl apply -f deployment/${CIRCLE_BRANCH}/deployment-${CIRCLE_BRANCH}.yml
            kubectl apply -f deployment/${CIRCLE_BRANCH}/service-${CIRCLE_BRANCH}.yml

      - run:
          name: Show the deployment result
          command: |
            kubectl get svc
            kubectl get pods -o wide
