version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.12

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14

      - run:
          name: Install hadolint
          command: sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m) && sudo chmod +x /bin/hadolint

      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile
          
      - run:
          name: Build and Push Docker Image
          command: |
            docker --version
            docker build -t mynameis .
            docker tag mynameis locbuii/mynameis:latest
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push locbuii/mynameis:latest
            
      - run:
          name: Install eksctl
          command: |
            sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | sudo tar xz -C /usr/local/bin

      - run:
          name: Create EKS cluster
          command: eksctl create cluster --name mynameis --region us-west-2 --node-type t2.medium --nodes-min 1 --nodes-max 3

      - run:
          name: Configure kubectl
          command: eksctl utils write-kubeconfig --name mynameis --region us-west-2
      
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl

      - run:
          name: Install aws-iam-authenticator
          command: |
            curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
            chmod +x aws-iam-authenticator
            sudo mv aws-iam-authenticator /usr/local/bin/
            
      - run:
          name: Verify kubectl installation
          command: kubectl version
          
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version

      - run:
          name: Deploy to Kubernetes Cluster
          command: |
            kubectl apply -f deployment/${CIRCLE_BRANCH}/deployment-${CIRCLE_BRANCH}.yml
            kubectl apply -f deployment/${CIRCLE_BRANCH}/service-${CIRCLE_BRANCH}.yml

      - run:
          name: Show the deployment result
          command: |
            kubectl get svc
            kubectl get pods -o wide
