version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.12

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build and Push Docker Image
          command: |
            docker --version
            docker build -t mynameis .
            docker tag mynameis locbuii/mynameis:latest
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push locbuii/mynameis:latest
            
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Verify AWS CLI installation
          command: aws --version

      - run:
          name: Create EKS Cluster
          command: |
            aws eks create-cluster --name mynameis-cluster --region us-east-1 --version 1.21 --nodegroup-name my-node-group --node-type t2.micro --nodes 3

      - run:
          name: Install kubectl
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https
            curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
            sudo apt-get update
            sudo apt-get install -y kubectl
            
      - run:
          name: Verify kubectl installation
          command: kubectl version --client

      - run:
          name: Deploy to Kubernetes Cluster
          command: |
            aws eks update-kubeconfig --name mynameis-cluster --region us-east-1
            kubectl apply -f deployment/${CIRCLE_BRANCH}/deployment-${CIRCLE_BRANCH}.yml
            kubectl apply -f deployment/${CIRCLE_BRANCH}/service-${CIRCLE_BRANCH}.yml

      - run:
          name: Show the deployment result
          command: |
            kubectl get svc
            kubectl get pods -o wide
